import type { Metadata } from 'next';
import './globals.css';
import React, { ReactElement } from 'react';
import { ThemeProvider } from '@/providers/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>): ReactElement {
  return (
    <html lang="en">
      <body className="--font-geist-sans --font-geist-mono antialiased">
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
